### ISSUE TITLE
Focus w/ Michał Czmiel

### ISSUE THREAD

**Issue by Mmnowski** [learn-geo-node/geo-node#5]
What to talk about:
 - Storing geo data in database
 - Handling admin accounts (general and an example (?) in node)
 - Tips for C4 model

**Comment by adrianghub** [comment]
MEET NOTES (21.06)

- look for a "jsonb" in postgresql
- consider 1 table with response data ( in
- intro to c4 [https://c4model.com/](https://c4model.com/)
- consider using this tool C4plantUML
- Handle admin account creation (cli/migration)
- https://stackoverflow.com/questions/46016139/best-user-role-permissions-database-design-practice
- https://jsonapi.org/
